// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA_SA_ZyjnYHz5MMK1S8FbOMLsSs2M6i4',
    appId: '1:411667724579:web:dde6f204b19a2c8e117496',
    messagingSenderId: '411667724579',
    projectId: 'medflow-499706',
    authDomain: 'medflow-499706.firebaseapp.com',
    storageBucket: 'medflow-499706.firebasestorage.app',
    measurementId: 'G-5YZJN9MJ5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPuWzVmNQgPGPyv--gcP5Mw6hT4j00NCo',
    appId: '1:411667724579:android:992ac9e333df14ab117496',
    messagingSenderId: '411667724579',
    projectId: 'medflow-499706',
    storageBucket: 'medflow-499706.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADG3Jm4-VhGzaP-0IwYMzuCyFSezR0WR4',
    appId: '1:411667724579:ios:b36c50d00ba684f5117496',
    messagingSenderId: '411667724579',
    projectId: 'medflow-499706',
    storageBucket: 'medflow-499706.firebasestorage.app',
    iosBundleId: 'com.example.mediflow',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADG3Jm4-VhGzaP-0IwYMzuCyFSezR0WR4',
    appId: '1:411667724579:ios:b36c50d00ba684f5117496',
    messagingSenderId: '411667724579',
    projectId: 'medflow-499706',
    storageBucket: 'medflow-499706.firebasestorage.app',
    iosBundleId: 'com.example.mediflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA_SA_ZyjnYHz5MMK1S8FbOMLsSs2M6i4',
    appId: '1:411667724579:web:1bc78a197b1e9452117496',
    messagingSenderId: '411667724579',
    projectId: 'medflow-499706',
    authDomain: 'medflow-499706.firebaseapp.com',
    storageBucket: 'medflow-499706.firebasestorage.app',
    measurementId: 'G-0RSYGDLVCQ',
  );
}
