// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaph0NtrAdeqgYFdCg4sBdS4wzIv8IfWQ',
    appId: '1:381834929556:web:a8dfb1d711a7ba427e5b81',
    messagingSenderId: '381834929556',
    projectId: 'mediflow-f1b78',
    authDomain: 'mediflow-f1b78.firebaseapp.com',
    storageBucket: 'mediflow-f1b78.firebasestorage.app',
    measurementId: 'G-3JMGTTG7MF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz5kO3mpraNzoCg6DAowCTMTeAHN34prw',
    appId: '1:381834929556:android:7618555b0d4f8c5c7e5b81',
    messagingSenderId: '381834929556',
    projectId: 'mediflow-f1b78',
    storageBucket: 'mediflow-f1b78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj4q23OpJGryejYcbYyrUNMp-nxxZ0Fgw',
    appId: '1:381834929556:ios:94bed3ddc0f71d137e5b81',
    messagingSenderId: '381834929556',
    projectId: 'mediflow-f1b78',
    storageBucket: 'mediflow-f1b78.firebasestorage.app',
    iosBundleId: 'com.example.mediflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj4q23OpJGryejYcbYyrUNMp-nxxZ0Fgw',
    appId: '1:381834929556:ios:94bed3ddc0f71d137e5b81',
    messagingSenderId: '381834929556',
    projectId: 'mediflow-f1b78',
    storageBucket: 'mediflow-f1b78.firebasestorage.app',
    iosBundleId: 'com.example.mediflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaph0NtrAdeqgYFdCg4sBdS4wzIv8IfWQ',
    appId: '1:381834929556:web:a9c7d44c037f7f3d7e5b81',
    messagingSenderId: '381834929556',
    projectId: 'mediflow-f1b78',
    authDomain: 'mediflow-f1b78.firebaseapp.com',
    storageBucket: 'mediflow-f1b78.firebasestorage.app',
    measurementId: 'G-BG772BE7BS',
  );

}