// lib/main.dart
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:mediflow/core/theme.dart';
import 'package:mediflow/core/notification_service.dart';
import 'package:mediflow/core/fcm_service.dart';
import 'package:mediflow/core/router.dart';
import 'package:mediflow/core/connectivity_wrapper.dart';
import 'firebase_options.dart';  // generated by FlutterFire CLI

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Lock to portrait orientation
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // Set status bar style
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.dark,
    ),
  );

  // ── Firebase ──────────────────────────────────────────────────────────────
  // Initialize Firebase first (required for both Phone Auth and FCM)
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Initialize FCM service (channels, background handler, foreground listener)
  try {
    await FcmService.instance.initialize();
  } catch (e) {
    debugPrint('FcmService init failed: $e');
  }

  // ── Local Notifications ───────────────────────────────────────────────────
  try {
    await NotificationService.instance.initialize();
  } catch (e) {
    debugPrint('NotificationService init failed: $e');
  }

  // ── Supabase ──────────────────────────────────────────────────────────────
  await Supabase.initialize(
    url: 'https://dtmkzvptamydlgubmzlb.supabase.co',
    anonKey: 'sb_publishable_30AYi1oyhTvuzqtcN-BsbQ_j4MnFKHv',
    debug: false,
  );

  runApp(
    const ProviderScope(
      child: MediFlowApp(),
    ),
  );
}

class MediFlowApp extends ConsumerWidget {
  const MediFlowApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(routerProvider);

    return MaterialApp.router(
      routerConfig: router,
      title: 'MediFlow',
      theme: AppTheme.neumorphicTheme,
      debugShowCheckedModeBanner: false,
      builder: (context, child) {
        return MediaQuery(
          data: MediaQuery.of(context).copyWith(
            textScaler: TextScaler.linear(
              MediaQuery.of(context).textScaler.scale(1.0).clamp(0.8, 1.2),
            ),
          ),
          child: ConnectivityWrapper(
            child: child ?? const SizedBox.shrink(),
          ),
        );
      },
    );
  }
}